import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import store from './store';
import vuetify from './plugins/vuetify';
import { loadFonts } from './plugins/webfontloader';
import VueSweetalert2 from 'vue-sweetalert2';
import 'sweetalert2/dist/sweetalert2.min.css';
import PopupHeader from '@/components/layout/PopupHeader.vue';
import ActionButton from '@/components/layout/ActionButton.vue';
import SelectComp from '@/components/vueti/SelectComp.vue';
// import useCmn from '@/composables/cmn';
import mitt from 'mitt';

loadFonts();
const app = createApp(App);
// app.config.globalProperties.$utils = useCmn();
app.config.globalProperties.$emitter = mitt();
app.component('PopupHeader', PopupHeader);
app.component('ActionButton', ActionButton);
app.component('SelectComp', SelectComp);
app.use(router).use(store).use(vuetify).use(VueSweetalert2).mount('#app');
